import type { Metadata } from "next";
import { Inter, Manrope, Poppins, Roboto } from 'next/font/google'
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const poppins = Poppins({
  weight: '400',
  variable: '--font-poppins',
  subsets: ['latin'],
})

const roboto = Roboto({
  weight: '400',
  variable: '--font-roboto',
  subsets: ['latin'],
})

const inter = Inter({
  weight: '400',
  variable: '--font-inter',
  subsets: ['latin'],
})

const manrope = Manrope({
  weight: '400',
  variable: '--font-manrope',
  subsets: ['latin'],
})

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) 
{
  return (
    <html lang="es">
      <body className=
        {`${roboto.variable} ${poppins.variable} ${inter.variable} ${manrope.variable}`}>
        {children}
      </body>
    </html>
  );
}
